component: nuxtjs
name: website-nuxt
org: orgDemo
app: appDemo
stage: dev

inputs:
  src:
    src: ./
    exclude:
      - .env
      - serverless.yml
  region: ap-guangzhou
  runtime: Nodejs10.15
  apigatewayConf:
    protocols:
      - http
      - https
    environment: release
